spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/api/client/**
        - Header=spring-cloud-course, \w*
        filters:
        - RemoveRequestHeader=spring-cloud-course
  application:
    name: api-gateway
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
