spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/api/client/**
        filters:
        - name: RequestHeader
          args:
            headerName: spring-cloud-course
        - RemoveRequestHeader=spring-cloud-course
      - id: client-update
        uri: lb://client-update
        predicates:
        - Path=/api/update/**

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
