version: '3.8'
services:
  spring_micro_demo_a_auth_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: spring_micro_demo_a_auth_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - '5421:5432'

