spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false #?? ????? ???????? ?????????? ??????? ?? eureka-server
    eureka-server-connect-timeout-seconds: 60 #????? ???????? ?? ????????? ????-???? ?????????? ? eureka-server
    eureka-service-url-poll-interval-seconds: 15 #?????? 15 ?????? ??????????? ????????? ?? ???? ? ???????
    use-dns-for-fetching-service-urls: false #????????? dns ? ??????? ????? ??????? ? ???????? eureka (serviceUrl)
    prefer-same-zone-eureka: true #???????????? ?????? eureka ? ??? ?? ????
    healthcheck:
      enabled: true #??? ??????? ??????? healthcheck
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.85 #???? ????????? ???????? ? ???? ??? ??? ?????? ?????? ?? ?????, ?? ????? ????????? ??????;
  instance:
    hostname: my-eureka-server.com
    metadata-map:
      zone: zone_A #???????????? ?????? eureka ? ??? ?? ????
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 70

